# Generated by Django 4.2.10 on 2024-03-02 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0005_alter_subscription_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='update',
            field=models.DateTimeField(auto_now=True, verbose_name='последнее обновление'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='update',
            field=models.DateTimeField(auto_now=True, verbose_name='последнее обновление'),
        ),
    ]
